server.port=53061
spring.kafka.consumer.bootstrap-servers=localhost:9092,localhost:9094
#spring.kafka.consumer.hey-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.group-id=product-created-events
# * is not recommended for production, specify the packages that contain your event classes
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.mhb.core